dist: xenial
language: java
jdk:
  - openjdk8
before_script:
  - curl -L https://github.com/nats-io/nats-streaming-server/releases/download/v0.15.1/nats-streaming-server-v0.15.1-linux-amd64.zip -o nats-streaming-server.zip
  - unzip nats-streaming-server.zip -d tmp
  - tmp/nats-streaming-server-v0.15.1-linux-amd64/nats-streaming-server &
script:
  - ./gradlew test --tests *CordaStateChangeListener* --tests nl.nuts.consent.bridge.nats*
  #- ./gradlew codeCoverageReport
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
