nuts:
  consent:
    schedule:
      delay: 15 * 60 * 1000
      initial_delay: 1000

spring:
  application:
    name: nutsConsentBridge

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

# Health information
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
