version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - run:
          name: Gradle tests
          command: |
            ./gradlew check
      - run:
          name: Upload coverage
          command: |
            ./gradlew codeCoverageReport
            bash <(curl -s https://codecov.io/bash)
