/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.registry.models


import com.squareup.moshi.Json

/**
* Domain the entity operates in.
* Values: healthcare,personal,insurance
*/
enum class Domain(val value: kotlin.String){

    @Json(name = "healthcare") healthcare("healthcare"),

    @Json(name = "personal") personal("personal"),

    @Json(name = "insurance") insurance("insurance");

}

