/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.registry.models


/**
 * 
 * @param type type of the event
 * @param issuedAt timestamp at which the event happened
 * @param signature JWS (JSON Web Signature) securing the payload's authenticity and integrity.
 * @param payload payload of the event
 */
data class Event (
    /* type of the event */
    val type: kotlin.String? = null,
    /* timestamp at which the event happened */
    val issuedAt: java.time.LocalDateTime? = null,
    /* JWS (JSON Web Signature) securing the payload's authenticity and integrity. */
    val signature: kotlin.String? = null,
    /* payload of the event */
    val payload: kotlin.Any? = null
) {

}

