/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.registry.models

import nl.nuts.consent.bridge.registry.models.Domain

/**
 * 
 * @param name the well-known name for the vendor
 * @param identifier Generic identifier used for representing BSN, agbcode, etc. It's always constructed as an URN followed by a double colon (:) and then the identifying value of the given URN 
 * @param domain 
 * @param orgKeys 
 */
data class RegisterVendorEvent (
    /* the well-known name for the vendor */
    val name: kotlin.String,
    /* Generic identifier used for representing BSN, agbcode, etc. It's always constructed as an URN followed by a double colon (:) and then the identifying value of the given URN  */
    val identifier: kotlin.String,
    val domain: Domain,
    val orgKeys: kotlin.Array<JWK>? = null
) {

}

