/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.registry.models

import nl.nuts.consent.bridge.registry.models.Domain

/**
 * 
 * @param name the well-known name for the vendor
 * @param domain 
 */
data class Vendor (
    /* the well-known name for the vendor */
    val name: kotlin.String,
    val domain: Domain
) {

}

