/**
* Nuts event store spec
* API specification for event store. The event store records the events of the in-flight transactions. 
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.events.models

import nl.nuts.consent.bridge.events.models.Event

/**
 * 
 * @param events 
 */
data class EventListResponse (
    val events: kotlin.Array<Event>? = null
) {

}

