/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.models


import com.squareup.moshi.Json
/**
 * 
 * @param endpointType URI of the type of endpoint
 * @param identifier Generic identifier used for representing BSN, agbcode, etc. It's always constructed as an URN followed by a double colon (:) and then the identifying value of the given URN 
 * @param status status of the endpoint
 * @param version version number of the endpoint, used to distinguish between upgrades of endpoint
 * @param URL location of the actual en endpoint on the internet
 */
data class Endpoint (
    /* URI of the type of endpoint */
    val endpointType: kotlin.String,
    /* Generic identifier used for representing BSN, agbcode, etc. It's always constructed as an URN followed by a double colon (:) and then the identifying value of the given URN  */
    val identifier: kotlin.String,
    /* status of the endpoint */
    val status: Endpoint.Status,
    /* version number of the endpoint, used to distinguish between upgrades of endpoint */
    val version: kotlin.String,
    /* location of the actual en endpoint on the internet */
    val URL: kotlin.String
) {

    /**
    * status of the endpoint
    * Values: active,disabled
    */
    enum class Status(val value: kotlin.String){
    
        @Json(name = "active") active("active"),
    
        @Json(name = "disabled") disabled("disabled");
    
    }

}

