/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.models

import nl.nuts.consent.bridge.models.Identifier

import com.squareup.moshi.Json
/**
 * Mapping between Endpoints and Organizations
 * @param endpointIdentifier 
 * @param organizationIdentifier 
 * @param status status of the endpoint
 */
data class EndpointOrganization (
    val endpointIdentifier: Identifier,
    val organizationIdentifier: Identifier,
    /* status of the endpoint */
    val status: EndpointOrganization.Status
) {

    /**
    * status of the endpoint
    * Values: active,disabled
    */
    enum class Status(val value: kotlin.String){
    
        @Json(name = "active") active("active"),
    
        @Json(name = "disabled") disabled("disabled");
    
    }

}

