/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.models


import com.squareup.moshi.Json
/**
 * Mapping between Endpoints and Organizations
 * @param endpoint Generic identifier used for representing BSN, agbcode, etc. It's always constructed as an URN followed by a double colon (::) and then the identifying value of the given URN 
 * @param organization Generic identifier used for representing BSN, agbcode, etc. It's always constructed as an URN followed by a double colon (::) and then the identifying value of the given URN 
 * @param status status of the endpoint
 */
data class EndpointOrganization (
    /* Generic identifier used for representing BSN, agbcode, etc. It's always constructed as an URN followed by a double colon (::) and then the identifying value of the given URN  */
    val endpoint: kotlin.String,
    /* Generic identifier used for representing BSN, agbcode, etc. It's always constructed as an URN followed by a double colon (::) and then the identifying value of the given URN  */
    val organization: kotlin.String,
    /* status of the endpoint */
    val status: EndpointOrganization.Status
) {

    /**
    * status of the endpoint
    * Values: active,disabled
    */
    enum class Status(val value: kotlin.String){
    
        @Json(name = "active") active("active"),
    
        @Json(name = "disabled") disabled("disabled");
    
    }

}

