/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.models


/**
 * 
 * @param system the code system used for this identifier
 * @param value the value, valid within the code system
 */
data class Identifier (
    /* the code system used for this identifier */
    val system: kotlin.String,
    /* the value, valid within the code system */
    val value: kotlin.String
) {

}

