/**
* Nuts registry API spec
* API specification for RPC services available at the nuts-registry
*
* OpenAPI spec version: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package nl.nuts.consent.bridge.models

import nl.nuts.consent.bridge.models.Identifier

/**
 * 
 * @param name the well-known name for the organization
 * @param identifier 
 */
data class Organization (
    /* the well-known name for the organization */
    val name: kotlin.String,
    val identifier: Identifier
) {

}

